### ISSUE TITLE
Solution to a Potential Error in Windows

### ISSUE THREAD

**Issue by robinnarsinghranabhat** [clemkoa/ntm#10]
Following this installation in windows, It gave me the following error when I tried to run :
`python copy_task.py --eval`

For anybody experiencing this, a quick workaround is : 
Paste this in `ntm/__init__.py`  : 

```python
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
```

The better solution that worked for me was using `python 3.8 `and `pytorch 1.7`

**Comment by clemkoa** [comment]
Hi, thank you for opening this issue! 
As you probably guessed I'm not developing on Windows so it's a bit tricky for me to reproduce this issue. I should be able to access a Windows machine in the next few weeks. 

In the meantime, would you please share the error you saw when running the python command. Is it only for the eval script or for the training one too?
Could you please elaborate on the different solutions you proposed? Is there a conflicting pytorch version with other dependencies? I don't know enough about Windows environment but it seems like none of your solutions are optimal. Editing the environment variable seems like a bad idea and we shouldn't have to switch python / pytorch versions to make this project work. I'm guessing there are conflicting dependencies and we should probably dig a bit deeper to see how to fix "properly". Happy to have a chat about it if you have more information.

Thanks again for opening this issue, I'm sure we'll get it to work properly on Windows soon! :)

**Comment by robinnarsinghranabhat** [comment]
For better or for worse, I re-did the installation with process described on second paragraph, and it's working all good. But now, I cannot reproduce [this](https://discuss.pytorch.org/t/ran-into-this-issue-while-executing/101460)  problem, which I had run into yesterday. 

What I can verify is, This installation works with conda in Windows  (I use conda for almost everything). So, maybe add this to the `README` for successful windows installation.
1. `conda create -n myenv python=3.9` 
2. `conda activate myenv` 
3. `pip install -r requirements.txt`

NOTE : make sure `pip` is from inside **myenv** || check using : `where pip`

**Comment by clemkoa** [comment]
Hi,
If this is okay I will close this issue due to inactivity. Feel free to open a PR if there are installation steps that we need to fix. Thanks again for your contributions to this repo
