### ISSUE TITLE
write_head should get previous_write_head_state

### ISSUE THREAD

**Issue by confifu** [clemkoa/ntm#8]
https://github.com/clemkoa/ntm/blob/f6da2984f9493c0078a7136c0cafbec7db077183/ntm/ntm.py#L35

I think this is a mistake. The `previous_write_head_state` variable is not used anywhere whereas both `read_head` and `write_head` get `previous_read_head_state`

**Comment by clemkoa** [comment]
It looks like you are right! Not sure how the model managed to converge with that mistake. I am testing this change locally and it seems to improve the training convergence. Thanks for spotting this one!

If you want to be listed as contributor you can open a pull request with the change, otherwise I'll make the change myself in the upcoming days.

**Comment by confifu** [comment]
Now that we are finding mistakes 😋  I am also confused about the `controller_state` returned here. 
https://github.com/clemkoa/ntm/blob/f6da2984f9493c0078a7136c0cafbec7db077183/ntm/ntm.py#L31
Looks like that variable just gets passed through batches and never gets used anywhere.

**Comment by clemkoa** [comment]
I'm not sure I understand your question here.
The previous_controller_state is fed in the same line to the controller, and that's how we get the new controller_state. How is that different to the read_head_state for instance?
Just as a note, the controller_state is never used for the feedforward controller, but is used in the LSTM controller. The LSTM is why I had to add it :) https://github.com/clemkoa/ntm/blob/f6da2984f9493c0078a7136c0cafbec7db077183/ntm/controller.py#L40

**Comment by confifu** [comment]
Yes, this is correct. That was a false alarm.

**Comment by clemkoa** [comment]
@confifu I have pushed a change to fix this. Thank you for your contribution, very appreciated!
