### ISSUE TITLE
Could this implementation be use to solve the parity issue?

### ISSUE THREAD

**Issue by ghost** [clemkoa/ntm#9]
Thank you for the nice work! 

I am wondering if your implementation can be used to classifying the parity (even or odd) of bitstring.
For example, 
input: [0, 1, 0, 1, 0, 0]  --> output 0
input: [0, 1, 0, 1, 0, 1]  --> output 1

If it can, how can I modify this code? Could you please give me a example? Thank you very much.

**Comment by clemkoa** [comment]
I'm not sure I understand the task you are describing, could elaborate please?

From what I understand, you want a model that will return the last element of a binary array input? If so, NTM might be overkill. I feel like a feedforward network would work, maybe a RNN/LSTM if the length of the sequence is variable. I don't see why we would need the memory addressing mechanisms of the NTM here. But I'm happy to think about it if I didn't understand your task correctly

**Comment by ghost** [comment]
I appreciate your reply and your consideration. I am sorry that I did not illustrate it well. The task is basically a binary classification where the input is a bitstring of given length of(like [0, 1, 1, 0, 1, 1]) and the output is the parity of it - which is 1 if the number of 1s in it is odd, or 0 if even - which is 0 in this case because it contains four 1s. It is a very interesting task. DeepMind published a paper(https://arxiv.org/pdf/2107.05407.pdf) several month ago, showing the performance of their model on the parity data. You can find more details about it at section 3.1. The implementation of this dataset can be found at https://github.com/jankrepl/mildlyoverfitted/blob/master/github_adventures/pondernet/utils.py. 

The parity is hard because it apparently requires memory to solve it. The RNN/LSTM can not handle it well unless the number of nodes increases with the input length. NTM might be capable of solving it as armed with memory. I would like to implement the model with your code, and compare its performance with other models. It would be very nice if I could get your help. Hope you also find it interesting.

**Comment by clemkoa** [comment]
Okay I understand better, thanks for the explanation. Sounds like NTM could be fit for this task and that the copy task is pretty similar to this.

My guess is that you would only have to change the output in this function https://github.com/clemkoa/ntm/blob/master/copy_task.py#L27, to return the parity instead of a copy of the input. And that should do it? Maybe a few parameters to change in the model itself but I feel like the logic should stay similar.

**Comment by ghost** [comment]
Thank you for the advice. I will definitely delve deep into the copy task and do some modifications. The model might also need to be tweaked, as the output would be a scale not a sequence. I will keep you updated! Thank you again.

**Comment by clemkoa** [comment]
Sounds good! Keep me posted on how it goes, it could be a great addition to the repo if it works!

**Comment by ghost** [comment]
Yeah, I hope it could work. I will start working on it next month and might need your help.

**Comment by clemkoa** [comment]
Hi, I will close this issue due to inactivity. Feel free to open a PR if you have something working. Thanks again for your contributions to this repo!
